version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=db;database=EvalDockerDB;user=root;password=root;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      api:
        condition: service_started
    networks:
      - app_net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EvalDockerDB
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_net:
    driver: bridge

volumes:
  db_data:
